platform:ios, ‘9.0‘


target :OTIS_PJ do
    
    pod 'AFNetworking'
    
    pod 'FMDB'
    
    pod 'MJExtension'
    
    pod 'INTULocationManager'
    
    pod 'LBXScan'
    
    pod 'MBProgressHUD', '~> 1.0.0'
    
    pod 'Masonry'
    
    pod 'iOS-blur'
    
    pod 'MMPopupView'

end







